services:
  - type: web
    name: ecosistema-nexus-web
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DATABASE_URL
        value: postgresql://nexus_postgres_db_user:cU0VInNSTcc69JZbDtuVnp2gOJx0AJEV@dpg-da2ssrflk1mc73cq2960-a.oregon-postgres.render.com/nexus_postgres_db

