# Generated by Django 4.2.30 on 2026-06-12 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('categoria', models.CharField(choices=[('TRABAJADOR', 'Trabajadores'), ('PATRONAL', 'Patronales')], default='TRABAJADOR', max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'unique_together': {('numero', 'categoria')},
            },
        ),
        migrations.CreateModel(
            name='Estante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estantes', to='ubicacion.modulo')),
            ],
            options={
                'unique_together': {('modulo', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Bandeja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('estante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bandejas', to='ubicacion.estante')),
            ],
            options={
                'unique_together': {('estante', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Cubiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('bandeja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cubiculos', to='ubicacion.bandeja')),
            ],
            options={
                'unique_together': {('bandeja', 'numero')},
            },
        ),
    ]
