# Generated by Django 4.2.30 on 2026-06-13 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0003_alter_carpeta_unique_together_carpeta_bandeja_and_more'),
        ('ubicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cubiculo',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='cubiculo',
            name='bandeja',
        ),
        migrations.AlterUniqueTogether(
            name='estante',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='estante',
            name='modulo',
        ),
        migrations.AlterUniqueTogether(
            name='modulo',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='Bandeja',
        ),
        migrations.DeleteModel(
            name='Cubiculo',
        ),
        migrations.DeleteModel(
            name='Estante',
        ),
        migrations.DeleteModel(
            name='Modulo',
        ),
    ]
