# Generated by Django 4.2.30 on 2026-10-01 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EncabezadoTRD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad_productora', models.CharField(max_length=200)),
                ('oficina_productora', models.CharField(max_length=200)),
                ('fecha_creacion', models.CharField(blank=True, max_length=50)),
                ('fecha_ajuste', models.CharField(blank=True, max_length=50)),
                ('fecha_aprobacion', models.CharField(blank=True, max_length=50)),
                ('fecha_convalidacion', models.CharField(blank=True, max_length=50)),
                ('responsable_gestion_documental', models.CharField(max_length=200)),
                ('cargo_responsable_gestion_documental', models.CharField(max_length=200)),
                ('responsable_area', models.CharField(blank=True, max_length=200)),
                ('cargo_responsable_area', models.CharField(blank=True, max_length=200)),
                ('superior_jerarquico', models.CharField(max_length=200)),
                ('cargo_superior_jerarquico', models.CharField(max_length=200)),
                ('version', models.CharField(default='1.0', max_length=50)),
                ('estado', models.CharField(default='VIGENTE', max_length=50)),
                ('vigencia_ano', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ItemTRD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=50)),
                ('nivel', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=500)),
                ('soporte_papel', models.BooleanField(default=False)),
                ('soporte_electronico', models.BooleanField(default=False)),
                ('extensiones', models.CharField(blank=True, max_length=200)),
                ('retencion_gestion', models.IntegerField(blank=True, null=True)),
                ('retencion_central', models.IntegerField(blank=True, null=True)),
                ('disposicion_final', models.CharField(blank=True, max_length=10)),
                ('reproduccion_tecnica', models.CharField(blank=True, max_length=50)),
                ('procedimiento', models.TextField(blank=True)),
                ('orden', models.IntegerField(default=0)),
                ('encabezado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='trd.encabezadotrd')),
            ],
        ),
    ]
