# Generated by Django 4.2.30 on 2026-06-12 20:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ubicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carpeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('TRABAJADOR', 'Trabajadores'), ('PATRONAL', 'Patronales')], default='TRABAJADOR', max_length=20)),
                ('nombre', models.CharField(max_length=255)),
                ('identificacion', models.CharField(max_length=50)),
                ('numero_carpeta', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(55)])),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('cubiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carpetas', to='ubicacion.cubiculo')),
            ],
            options={
                'unique_together': {('categoria', 'cubiculo', 'numero_carpeta')},
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('SUPER', 'SuperUsuario'), ('ADMIN_DEP', 'Admin Dependencia'), ('ASESOR', 'Asesor')], default='ASESOR', max_length=20)),
                ('dependencia', models.CharField(blank=True, choices=[('GLOBAL', 'Dirección General'), ('VENTANILLA', 'Ventanilla Única'), ('APORTES', 'Aportes y Pagos'), ('SERVICIOS', 'Servicios Sociales'), ('JURIDICA', 'Oficina Jurídica'), ('FINANCIERA', 'Oficina Financiera'), ('ARCHIVO', 'Archivo Central / Gestión Documental')], default='VENTANILLA', max_length=20, null=True)),
                ('email_sincronizacion', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_password', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialCarpeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('carpeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='afiliados.carpeta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
