# Generated by Django 4.2.30 on 2026-06-13 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0002_carpeta_estado_excel_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carpeta',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='carpeta',
            name='bandeja',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='carpeta',
            name='estante',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='carpeta',
            name='modulo',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='carpeta',
            name='cubiculo',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='carpeta',
            unique_together={('categoria', 'modulo', 'estante', 'bandeja', 'cubiculo', 'numero_carpeta')},
        ),
    ]
