# Generated by Django 4.2.30 on 2026-06-13 07:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0003_alter_carpeta_unique_together_carpeta_bandeja_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpeta',
            name='bandeja',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='carpeta',
            name='cubiculo',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='carpeta',
            name='numero_carpeta',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(55)]),
        ),
    ]
