# Generated by Django 4.2.30 on 2026-06-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0004_alter_carpeta_bandeja_alter_carpeta_cubiculo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dependencia',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email_password',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email_sincronizacion',
        ),
        migrations.AlterField(
            model_name='profile',
            name='rol',
            field=models.CharField(choices=[('SUPER', 'SuperUsuario'), ('ASESOR', 'Asesor')], default='ASESOR', max_length=20),
        ),
    ]
