# Generated by Django 4.2.30 on 2026-06-16 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0005_remove_profile_dependencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='acceso_web',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rol',
            field=models.CharField(choices=[('SUPER', 'SuperUsuario'), ('JEFE', 'Jefe de Área'), ('USER', 'Usuario Consulta/Carga')], default='USER', max_length=20),
        ),
    ]
